### ISSUE TITLE
MIND: MIcrosoft News Dataset

### ISSUE THREAD

**Issue by c-nova** [microsoft/machine-learning-collection#2]
Please add the 'MIND: MIcrosoft News Dataset' to dataset chapter.
https://msnews.github.io/

This dataset is regarding to a paper below:
Fangzhao Wu, Ying Qiao, Jiun-Hung Chen, Chuhan Wu, Tao Qi, Jianxun Lian, Danyang Liu, Xing Xie, Jianfeng Gao, Winnie Wu and Ming Zhou. MIND: A Large-scale Dataset for News Recommendation. ACL 2020.

**Comment by konabuta** [comment]
@c-nova Thanks for the feedback! We will review and update accordingly.

**Comment by konabuta** [comment]
@c-nova  Thank you for your contribution! I add MIND dataset.
